Added copy as insert and copy as update
sosedoff/pgweb pull request #658
Opened 2023-02-28 21:50 UTC by jonaz

Fixes #649

2023-03-07 15:37 UTC, sosedoff requested changes

2023-03-07 15:37 UTC, sosedoff commented on static/js/app.js
> +        case "copy_as_insert":
Can you wrap functionality from `copy_as_*` into a separate function to keep the handler function small?

2023-03-07 15:37 UTC, sosedoff commented on static/js/app.js
> +  let columns = [];
Indentation on the following code is all messed up.

2023-03-07 15:37 UTC, sosedoff commented on static/js/app.js
> +function getValuesFromContext(context){
Indentation on the following code is all messed up, please fix. Also remove the commented out line.

2023-05-05 18:38 UTC, jonaz commented
@sosedoff updated the commit with requested changes. Also make error when table is not selected. Could not find another way to figure out the table name.

2023-06-28 18:28 UTC, jonaz commented
Ping @sosedoff ?

2023-06-30 01:40 UTC, sosedoff commented
This looks good so far. One thing that may need to be addressed -- context menu does not work correctly when in query editor. Steps to reproduce:

1. Refresh pgweb page
2. Go to sql editor and run a query that returns some results
3. Right click on one of the rows - select copy as insert (will complain about table, thats expected)
4. Click on any table in the sidebar, it should render its contents
5. Navigate back to the sql editor, run the existing query again.
6. Right click on one of the rows - it will incorrectly copy insert statement using previously selected tables.

Id suggest we disable the context menu options on sql query results  page.

2023-12-15 21:45 UTC, a-patos commented
Hello,
 is there any hope that MR will be successful one day or do we move on?

2024-03-15 05:32 UTC, sosedoff commented
Closing for the time being. Im happy to revisit if OP is interested in continuing the work.

2024-03-15 05:32 UTC, closed without merging

2024-03-15 07:26 UTC, jonaz commented
Yes im interested @sosedoff

2024-04-10 09:31 UTC, jonaz commented
New PR here https://github.com/sosedoff/pgweb/pull/730

2025-10-16 10:33 UTC, jonaz commented
ping @sosedoff ?